### ISSUE TITLE
FlowYouTube Exception

### ISSUE THREAD

**Issue by chococlat** [Garulf/FlowYouTube#12]
After installing FlowYouTube and typing `yt`, i get this error:
```
Please open new issue in: https://github.com/Garulf/FlowYouTube/issues/new
1. upload log file: C:\Users\cecco\AppData\Roaming\FlowLauncher\Logs\1.9.5\2022-10-07.txt
2. copy below exception message

Flow Launcher version: 1.9.5
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: 
Date: 10/07/2022 15:29:03
Exception:
FlowYouTube Exception: 
Websites: https://github.com/Garulf/FlowYouTube
Author: Garulf
Version: 1.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Access is denied.
 ---> System.ComponentModel.Win32Exception (5): Access is denied.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 247
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 322
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 34
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass137_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 616
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 590
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

Note that this is not the only plugin that's not working. This is also happening with other ones in the store, including some of yours. If needed i can check wich one specifically.

Im attaching also the log file. Te last entry is the one about FlowYouTube
[2022-10-07.txt](https://github.com/Garulf/FlowYouTube/files/9734312/2022-10-07.txt)
Thanks for your time
Alessandro

**Comment by KyleKolander** [comment]
I am also getting an this exception.

**Comment by Garulf** [comment]
According to the log Flow Launcher isn't able to access the plugin at all. 


Could you please answer these troubleshooting questions?

- Check the permissions on the plugins folder at `%appdata%\Flow Launcher\Plugins`. Simply right click the folder for `FlowYouTube` and click the permissions tab. Does your account have read/write/execute access?

- Are you running Flow Launcher as an administrator? This may cause issues if you try and run Flow Launcher as a non-Admin user. 

- Have you tried uninstalling and reinstalling? It may clear up the permissions issue. 

- Are you running Flow Launcher in a non-standard way? The plugins are simply zip files that Flow Launcher downloads and extracts to its plugin folder. It _should_ have the same permissions Flow Launcher has.

**Comment by KyleKolander** [comment]
I don't have that folder: `%appdata%\Flow Launcher\Plugins`.

I have it set to Start Flow Launcher on system startup.

I have not tried uninstalling and reinstalling.

I installed Flow Launcher via Scoop.

FWIW, almost all of the other plugins work as expected.  The only two I found that didn't work are the two for which I created issues.
