### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by m24ih** [Garulf/FlowYouTube#16]
Flow Launcher version: 1.13.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\melih\AppData\Local\Programs\Python\Python37-32\pythonw.exe
Node Path: 
Date: 02/20/2023 22:41:13
Exception:
FlowYouTube Exception: 
Websites: https://github.com/Garulf/FlowYouTube
Author: Garulf
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\melih\Desktop\FlowLauncher\app-1.13.0\UserData\Plugins\FlowYouTube-2.0.0\run.py", line 9, in <module>
    from plugin.main import FlowYouTube
  File "C:\Users\melih\Desktop\FlowLauncher\app-1.13.0\UserData\Plugins\FlowYouTube-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox, utils, ICON_BROWSER
  File "C:\Users\melih\Desktop\FlowLauncher\app-1.13.0\UserData\Plugins\FlowYouTube-2.0.0\lib\flox\__init__.py", line 13, in <module>
    from functools import wraps, cached_property
ImportError: cannot import name 'cached_property' from 'functools' (C:\Users\melih\AppData\Local\Programs\Python\Python37-32\lib\functools.py)

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\melih\Desktop\FlowLauncher\app-1.13.0\UserData\Plugins\FlowYouTube-2.0.0\run.py", line 9, in <module>
    from plugin.main import FlowYouTube
  File "C:\Users\melih\Desktop\FlowLauncher\app-1.13.0\UserData\Plugins\FlowYouTube-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox, utils, ICON_BROWSER
  File "C:\Users\melih\Desktop\FlowLauncher\app-1.13.0\UserData\Plugins\FlowYouTube-2.0.0\lib\flox\__init__.py", line 13, in <module>
    from functools import wraps, cached_property
ImportError: cannot import name 'cached_property' from 'functools' (C:\Users\melih\AppData\Local\Programs\Python\Python37-32\lib\functools.py)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 213
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 821
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 822
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
[2023-02-20.txt](https://github.com/Garulf/FlowYouTube/files/10787395/2023-02-20.txt)

**Comment by Garulf** [comment]
I see you’re using Flow Launcher with Python version 3.7. Flow Launcher uses 3.8 and above and most plugins are built and tested on this version. 

Please use Python 3.8 and you'll issue will be fixed.
