### ISSUE TITLE
Plugin issue

### ISSUE THREAD

**Issue by jpsapara** [Garulf/FlowYouTube#17]
Flow Launcher version: 1.14.0
OS Version: Microsoft Windows NT 10.0.22624.0
IntPtr Length: 8
x64: True

Python Path: C:\Users\JPSA\AppData\Roaming\FlowLauncher\Environments\Python\PythonEmbeddable-v3.8.9\pythonw.exe
Node Path: 
Date: 03/11/2023 10:42:09
Exception:
FlowYouTube Exception: 
Websites: https://github.com/Garulf/FlowYouTube
Author: Garulf
Version: 2.0.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "C:\Users\JPSA\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.0.0\run.py", line 9, in <module>
    from plugin.main import FlowYouTube
  File "C:\Users\JPSA\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox, utils, ICON_BROWSER
  File "C:\Users\JPSA\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.0.0\lib\flox\__init__.py", line 50, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "C:\Users\JPSA\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.0.0\run.py", line 9, in <module>
    from plugin.main import FlowYouTube
  File "C:\Users\JPSA\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.0.0\plugin\main.py", line 4, in <module>
    from flox import Flox, utils, ICON_BROWSER
  File "C:\Users\JPSA\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.0.0\lib\flox\__init__.py", line 50, in <module>
    raise FileNotFoundError("Unable to locate Launcher directory")
FileNotFoundError: Unable to locate Launcher directory

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 191
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 190
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 210
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 839
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 803
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
Sorry I haven't had a chance to respond. Just wanted to let you know I'm looking into your issue.
