### ISSUE TITLE
Flow Launcher got an error

### ISSUE THREAD

**Issue by SgtDragon** [Garulf/FlowYouTube#23]
[2023-06-06.txt](https://github.com/Garulf/FlowYouTube/files/11661887/2023-06-06.txt)

Flow Launcher version: 1.15.0
OS Version: 18362.1256
IntPtr Length: 8
x64: True

Python Path: C:\Users\micha\AppData\Local\Programs\Python\Python37\pythonw.exe
Node Path: 
Date: 06/06/2023 10:07:51
Exception:
FlowYouTube Exception: 
Websites: https://github.com/Garulf/FlowYouTube
Author: Garulf
Version: 2.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: Traceback (most recent call last):
  File "E:\FlowLauncher\app-1.15.0\UserData\Plugins\FlowYouTube-2.1.0\run.py", line 9, in <module>
    from plugin.main import FlowYouTube
  File "E:\FlowLauncher\app-1.15.0\UserData\Plugins\FlowYouTube-2.1.0\plugin\main.py", line 4, in <module>
    from flox import Flox, utils, clipboard, ICON_BROWSER, ICON_COPY
  File "E:\FlowLauncher\app-1.15.0\UserData\Plugins\FlowYouTube-2.1.0\lib\flox\__init__.py", line 13, in <module>
    from functools import wraps, cached_property
ImportError: cannot import name 'cached_property' from 'functools' (C:\Users\micha\AppData\Local\Programs\Python\Python37\lib\functools.py)

 ---> System.IO.InvalidDataException: Traceback (most recent call last):
  File "E:\FlowLauncher\app-1.15.0\UserData\Plugins\FlowYouTube-2.1.0\run.py", line 9, in <module>
    from plugin.main import FlowYouTube
  File "E:\FlowLauncher\app-1.15.0\UserData\Plugins\FlowYouTube-2.1.0\plugin\main.py", line 4, in <module>
    from flox import Flox, utils, clipboard, ICON_BROWSER, ICON_COPY
  File "E:\FlowLauncher\app-1.15.0\UserData\Plugins\FlowYouTube-2.1.0\lib\flox\__init__.py", line 13, in <module>
    from functools import wraps, cached_property
ImportError: cannot import name 'cached_property' from 'functools' (C:\Users\micha\AppData\Local\Programs\Python\Python37\lib\functools.py)

   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 294
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 299
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 314
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass22_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 194
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 216
   at Flow.Launcher.ViewModel.MainViewModel.<>c__DisplayClass135_0.<<QueryResults>g__QueryTask|2>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 836
--- End of stack trace from previous location ---
   at Flow.Launcher.ViewModel.MainViewModel.QueryResults() in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 800
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Garulf** [comment]
This plugin requires Python version 3.8 or possibly higher. 

Once updated the plugin should work without issue.
