### ISSUE TITLE
FlowYouTube Failed to respond

### ISSUE THREAD

**Issue by furtherafay** [Garulf/FlowYouTube#27]
Python Path: C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Doc\html\index.html
Node Path: 
Date: 09/25/2024 06:24:56
Exception:
FlowYouTube Exception: 
Websites: https://github.com/Garulf/FlowYouTube
Author: Garulf
Version: 2.1.0
Flow.Launcher.Core.ExternalPlugins.FlowPluginException: An error occurred trying to start process 'C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Doc\html\index.html' with working directory 'C:\Users\Administrator\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0'. The specified executable is not a valid application for this OS platform.
 ---> System.ComponentModel.Win32Exception (193): An error occurred trying to start process 'C:\Users\Administrator\AppData\Local\Programs\Python\Python312\Doc\html\index.html' with working directory 'C:\Users\Administrator\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0'. The specified executable is not a valid application for this OS platform.
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.ExecuteAsync(ProcessStartInfo startInfo, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 196
   at Flow.Launcher.Core.Plugin.JsonRPCPlugin.QueryAsync(Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\JsonRPCPlugin.cs:line 261
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_0.<<QueryForPluginAsync>b__0>d.MoveNext() in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 248
--- End of stack trace from previous location ---
   at Flow.Launcher.Infrastructure.Stopwatch.DebugAsync(String message, Func`1 action) in C:\projects\flow-launcher\Flow.Launcher.Infrastructure\Stopwatch.cs:line 40
   at Flow.Launcher.Core.Plugin.PluginManager.QueryForPluginAsync(PluginPair pair, Query query, CancellationToken token) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 282
   --- End of inner exception stack trace ---
   at Flow.Launcher.Core.Plugin.PluginManager.<>c__DisplayClass28_1.<QueryForPluginAsync>b__1(ActionContext _) in C:\projects\flow-launcher\Flow.Launcher.Core\Plugin\PluginManager.cs:line 276
   at Flow.Launcher.Plugin.Result.ExecuteAsync(ActionContext context) in /_/Flow.Launcher.Plugin/Result.cs:line 246
   at Flow.Launcher.ViewModel.MainViewModel.OpenResultAsync(String index) in C:\projects\flow-launcher\Flow.Launcher\ViewModel\MainViewModel.cs:line 389
   at CommunityToolkit.Mvvm.Input.AsyncRelayCommand.AwaitAndThrowIfFailed(Task executionTask)
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

[2024-09-25.txt](https://github.com/user-attachments/files/17131636/2024-09-25.txt)

**Comment by Garulf** [comment]
The log seems to show that the plugin is either missing or you do not have the correct permissions to run. 

Please try reinstalling and using the embedded Python 3.11 Flow Launcher provides.

**Comment by furtherafay** [comment]
Yes thank you it's working fine now

**Comment by Garulf** [comment]
Glad to hear! Closing issue.
