### ISSUE TITLE
ConnectionError

### ISSUE THREAD

**Issue by angelo-insanne** [Garulf/FlowYouTube#28]
Please type any relevant information here

<details open><summary>Trace Log</summary>
<p>

```
Traceback (most recent call last):
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\urllib3\util\connection.py", line 95, in create_connection
    raise err
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\urllib3\util\connection.py", line 85, in create_connection
    sock.connect(sa)
PermissionError: [WinError 10013] Foi feita uma tentativa de acesso a um soquete de uma maneira que é proibida pelas permissões de acesso

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\urllib3\connection.py", line 363, in connect
    self.sock = conn = self._new_conn()
                       ^^^^^^^^^^^^^^^^
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x000001897D4BABD0>: Failed to establish a new connection: [WinError 10013] Foi feita uma tentativa de acesso a um soquete de uma maneira que é proibida pelas permissões de acesso

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\requests\adapters.py", line 440, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\urllib3\util\retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='youtube.com', port=443): Max retries exceeded with url: /results?search_query=ps5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001897D4BABD0>: Failed to establish a new connection: [WinError 10013] Foi feita uma tentativa de acesso a um soquete de uma maneira que é proibida pelas permissões de acesso'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\flox\launcher.py", line 44, in run
    results = request_method(*request_parameters) or self._results
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\flox\__init__.py", line 131, in _query
    self.query(query)
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\plugin\main.py", line 43, in query
    self._results = utils.cache(
                    ^^^^^^^^^^^^
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\flox\utils.py", line 41, in wrapper
    data = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\plugin\main.py", line 50, in search
    results = YoutubeSearch(
              ^^^^^^^^^^^^^^
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\youtube_search\__init__.py", line 24, in __init__
    self.videos = self._search()
                  ^^^^^^^^^^^^^^
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\youtube_search\__init__.py", line 31, in _search
    response = self.session.get(url).text
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\requests\sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\requests\sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\requests\sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Angelo\AppData\Roaming\FlowLauncher\Plugins\FlowYouTube-2.1.0\lib\requests\adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='youtube.com', port=443): Max retries exceeded with url: /results?search_query=ps5 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x000001897D4BABD0>: Failed to establish a new connection: [WinError 10013] Foi feita uma tentativa de acesso a um soquete de uma maneira que é proibida pelas permissões de acesso'))

```
</p>
</details>

**Comment by Garulf** [comment]
Seems to be some sort of networking issue. Please make sure your network connection is available and YouTube is not blocked.
